### ISSUE TITLE
Del variants

### ISSUE THREAD

**Issue by mredrejo** [gersteinlab/ThermoNet#1]
Hi, thanks for sharing this resource. 
I'm about to try it and I wonder how to include multiple mutations and/or deletions in the variant list file.

Thanks!

**Comment by computbiolgeek** [comment]
Hi Modesto, thanks for the interest. Currently, only single-point mutations are supported. We will consider adding multi-site mutations and indels in future versions of the method.

**Comment by mredrejo** [comment]
Thanks for your quick answer.  That would be great for protein engineering purposes in our and other labs. 
I'm looking forward to new developments.

**Comment by computbiolgeek** [comment]
Yeah, absolutely. If you're interested and have the time, one approach to make an updated method would be to increase the dimension of the grid from 16 * 16 * 16 to, say, 100 * 100 * 100, in which case, the grid will span all the space occupied by a reasonably sized protein. Then, no matter how many mutations you have in the protein, the grid will take into account all of them. This is just a thought, I have not had the time to do it, and also not sure if there is enough data to train such an updated predictor. --Bian
