### ISSUE TITLE
Reverse mutation prediction

### ISSUE THREAD

**Issue by zhaiyj870912** [gersteinlab/ThermoNet#2]
Do you mind sharing how is reverse mutation prediction performed?
Thanks.

**Comment by computbiolgeek** [comment]
Hi, as described in the README, if the purpose is to make predictions for reverse mutations, add the `--reverse` flag to the `gends.py` command:
`gends.py -i VARIANT_LIST -o test_reverse_stacked_16_1 -p /path/to/where/all/XXXXX_relaxed.pdb/is/stored --boxsize 16 --voxelsize 1 --reverse`
I hope this helps.
