### ISSUE TITLE
Slow relax step

### ISSUE THREAD

**Issue by davidfstein** [gersteinlab/ThermoNet#4]
The documentation mentions that the relax step should take about a minute. I'm finding that even when reducing the max cycles to 200, the relax step takes quite a long time, maybe closer to 30 minutes or an hour. And similarly for the mutated structures. Is there anything in particular that you found speeds up this process beyond reducing the max cycles?

**Comment by computbiolgeek** [comment]
Dear David, thanks for your comment. This part of the documentation isn't the most accurate. Depending on the size of the protein, Rosetta's fast relaxation can still take a very long time (like hours).  I will update the documentation to reflect this. One way to speed up is to only relax the wild-type structure. Then use Rosetta fixbb protocol to make mutant structures. fixbb is very fast (minutes or less). However, I did not test by how much structures created by fixbb will affect the accuracy of ddG prediction. --Bian

**Comment by davidfstein** [comment]
Got it, thanks!
