### ISSUE TITLE
Problems in loading module utils and htmd

### ISSUE THREAD

**Issue by chenludi** [gersteinlab/ThermoNet#6]
I had problem import utils and htmd but other modules such as biopython can be imported.

1. I tried reconstruct a new conda environment the environment file (condaenvli.yaml, attached the file as 
[condaenvli.txt](https://github.com/gersteinlab/ThermoNet/files/9729194/condaenvli.txt)): 
$conda env create --prefix=/mydir/condaenvli1003 --file=condaenvli.yaml

2. utils is not included in the environment file [condaenvli.yaml], thus I installed utils after activating the conda env. May I ask I installed the required "utils" module?

$conda activate /mydir/condaenvli_1003
$pip install utils
Collecting utils
  Using cached utils-1.0.1-py2.py3-none-any.whl (21 kB)
Installing collected packages: utils
Successfully installed utils-1.0.1

However, utils is not found. 
$ python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from utils import pdb_utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>

ImportError: cannot import name 'pdb_utils' from 'utils' (/mydir/condaenvli1003/lib/python3.7/site-packages/utils/__init__.py)

3. htmd cannot be loaded correctly
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from htmd.ui import *
2022-10-06 16:12:56,298 - numexpr.utils - INFO - Note: detected 96 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2022-10-06 16:12:56,298 - numexpr.utils - INFO - Note: NumExpr detected 96 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.

Please cite HTMD: Doerr et al.(2016)JCTC,12,1845. https://dx.doi.org/10.1021/acs.jctc.6b00049
HTMD Documentation at: https://software.acellera.com/htmd/

2022-10-06 16:13:01,977 - binstar - INFO - Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mydir/condaenvli1003/lib/python3.7/site-packages/htmd/ui.py", line 82, in <module>
    compareVersions()
  File "/mydir/condaenvli1003/lib/python3.7/site-packages/htmd/latest.py", line 33, in compareVersions
    _writeLatestVersionFile(__file)
  File "/mydir/condaenvli1003/lib/python3.7/site-packages/htmd/latest.py", line 110, in _writeLatestVersionFile
    f.write("{} {}\n{} {}".format(stable, ",".join(stabledeps), dev, ",".join(devdeps)))
TypeError: can only join an iterable

**Comment by chenludi** [comment]
The problem has been solved! 

I contacted the developer of htmd and they updated a new version to solve the glibc incompatibility. Please find more info here: https://github.com/Acellera/htmd/issues/1038

The issue might be related to 1. the version of anaconda: installing htmd=2.1.6 by anaconda/2022.05 2. the server for registration of htmd had some problems during these days

Thank you for the help!

**Comment by computbiolgeek** [comment]
Hello Ludi, thanks for posting your update/solution here. Yeah, the incompatibility issue was our initial suspicion but we weren't able to find a solution to it. Glad you now had the issue resolved. I am now closing this issue, but feel free to reach out if you run into other issues.
