### ISSUE TITLE
Multiprocessing of relax step (rosetta_relax.py)?

### ISSUE THREAD

**Issue by YumuTabuchi** [gersteinlab/ThermoNet#8]
Relax step (rosetta_relax.py) takes about 2min per one variant on my desktop.
But only ~15% CPU and 1GB memory is used (maybe single process).
Is there any way to speed up this process?

I tried [MPI (the Message Passing Interface)](https://www.rosettacommons.org/docs/latest/build_documentation/Build-Documentation#setting-up-rosetta-3_alternative-setup-for-individual-workstations_message-passing-interface-mpi) but it didn't improve the speed.
Is it good that modifying rosetta_relax.py so that each variant is handled by multiple processes?

**Comment by computbiolgeek** [comment]
Thanks for the question. I am afraid that it isn't easy to handle each variant with multiple processes using Rosetta. However, what can be done is to run multiple relax jobs, one job for each batch of variants. For example, say if you have 100 variants, you can split it into 10 batches, with 10 variants in each batch. Then, run 10 parallel jobs. Hope this helps.

**Comment by YumuTabuchi** [comment]
Thanks for your replay!
Yes, I'll try the parallel process you suggested.
